library('bagfoot');
# This script runs "BaGFoot" on an example data set.


numcores = 2;      # No. of CPU cores to be used
options("bagfoot.mc.cores"=numcores);
options("bagfoot.mc.cores.motif"=numcores);


fed <- CutCount(file = "example_data/cutcount/fed_AC_cutcount_chr7.bgr.gz",   # BedGraph file of cut counts (see "bigfoot_prep_example.R")
									count = 97573026,						  # Number of cuts within the hotspots
									name = "fed");                            # Data Name 

fasted <- CutCount(file = "example_data/cutcount/fasted_AC_cutcount_chr7.bgr.gz", # BedGraph file of cut counts (see "bigfoot_prep_example.R")
									count = 118956736,							  # Number of cuts within the hotspots
									name = "fasted");							 # Data Name 	
 
motifdb_mm9 <- MotifDB(motiflistfile = 'example_data/motiflist_mm9motif62_chr7.txt',   # This file contains the list of FIMO outputs file
							directory='example_data/mm9_fimo_chr7/');				   # Directory of FIMO outputs

################fed VS fasted ##############

gfootoption_fed_fasted <- GFootOption(biasfile = "example_data/Hexamer_fed_fasted_merged_withMap.csv",   # Hexamer bias frequency table (see "bigfoot_prep_example.R")
						hexamer_pattern= "example_data/nuccode/nuccode_mm9_6mer_{chr}.mm9.dat");		 # nuc. code files generated by MakeBiasCorrectionTableBAM 

# For example, if "nuccode_XX_chr1.YY.dat", "nuccode_XX_chr2.YY.dat","nuccode_XX_chr3.YY.dat", ... are generated,
# hexamer_pattern should be given as "nuccode_XX_{chr}.YY.dat".


# Definition of BiGFoot analysis 
GFoot_fed_fasted= GFoot(control = fed,               ##  Control Data defined above
						treatment = fasted, 		 ##  Treatment Data defined above
						sitefile = "example_data/pooled_fed_fasted_merged_hotspot_chr7.csv",  ##  Sites file: Peak File.  This file must have "chr", "st", "ed" in the header.
						motifDB = motifdb_mm9,                 ##  Information about FIMO motifs
						gfootoption= gfootoption_fed_fasted,   ##  Options as defined above
						outputdir = "OUTPUT_fed_vs_fasted",  ## OUTPUT directory
						cachedir = "CACHE_fed_vs_fasted");   ## CACHE directory 


testresult = test_bagfoot_input(GFoot_fed_fasted); 

if (testresult) {
						
	GFoot_fed_fasted <- run(GFoot_fed_fasted, graphout=T,yrange=c(-2.2,1.0),mc.cores=numcores);   # if graphout is T, aggregation & log-ratio plots are to be generated.  
	# As an output, the output file 'fed_fasted_On_pooled_fed_fasted_merged_hotspot_chr7_footprint_depth_table.csv' will be generated.

	dat= read.table('fed_fasted_On_pooled_fed_fasted_merged_hotspot_chr7_footprint_depth_table.csv');
	gen_bagplot(dat, dataname1='Fed', dataname2='Fasted', factor=1.5);   # generates a bagplot from the calculated footprinting depths

}
