library('bagfoot');
# This script runs "BaGFoot" on an example data set.

numcores = 8;      # No. of CPU cores to be used
options("bagfoot.mc.cores"=numcores);
options("bagfoot.mc.cores.motif"=numcores);


fed <- CutCount(file = "inputdata/24h1_AC_cutcount.bgr.gz",   # BedGraph file of cut counts (see "bigfoot_prep_example.R")
		count = 468200526,						  # Number of cuts within the hotspots
		name = "24h");                            # Data Name 

fasted <- CutCount(file = "inputdata/control1_AC_cutcount.bgr.gz", # BedGraph file of cut counts (see "bigfoot_prep_example.R")
		   count = 475478080,							  # Number of cuts within the hotspots
		   name = "control");							 # Data Name 	
 
motifdb <- MotifDB(motiflistfile = 'inputdata/motiflist_mm10_cisbp_filtered.txt',   # This file contains the list of FIMO outputs file
		directory='inputdata/mm10_cisbp_fimo');				   # Directory of FIMO outputs

################fed VS fasted ##############
###### merge 24h and control bam file with picard and run bagfootBam.R to generat
gfootoption_fed_fasted <- GFootOption(biasfile = "inputdata/943678606_merged_mm10_withMap.txt",   # Hexamer bias frequency table (see "bigfoot_prep_example.R")
				      hexamer_pattern= "nuccode_control_24h_mm10/nuccode_mm10_6mer_{chr}.dat");		 # nuc. code files generated by MakeBiasCorrectionTableBAM 

# For example, if "nuccode_XX_chr1.YY.dat", "nuccode_XX_chr2.YY.dat","nuccode_XX_chr3.YY.dat", ... are generated,
# hexamer_pattern should be given as "nuccode_XX_{chr}.YY.dat".


# Definition of BiGFoot analysis 
GFoot_fed_fasted= GFoot(control = fasted,               ##  Control Data defined above
			treatment = fed, 		 ##  Treatment Data defined above
			sitefile = "hot2pot/ArchRPeakSet.csv",  ##  Sites file: Peak File.  This file must have "chr", "st", "ed" in the header.
			motifDB = motifdb,                 ##  Information about FIMO motifs
			gfootoption= gfootoption_fed_fasted,   ##  Options as defined above
			outputdir = "OUTPUT_fed_vs_fasted",  ## OUTPUT directory
			cachedir = "CACHE_fed_vs_fasted");   ## CACHE directory 

#saveRDS(GFoot_fed_fasted,"inputdata/GFoot_fed_fasted.rds")
testresult = test_bagfoot_input(GFoot_fed_fasted)
if (testresult) {
						
	GFoot_fed_fasted <- run(GFoot_fed_fasted, graphout=T,yrange=c(-2.2,1.0),mc.cores=numcores);   # if graphout is T, aggregation & log-ratio plots are to be generated.  
	saveRDS(GFoot_fed_fasted,"inputdata/GFoot_fed_fasted.rds")
	# As an output, the output file 'fed_fasted_On_pooled_fed_fasted_merged_hotspot_chr7_footprint_depth_table.csv' will be generated.
	#dat= read.table('fed_fasted_On_pooled_fed_fasted_merged_hotspot_chr7_footprint_depth_table.csv');
	#gen_bagplot(dat, dataname1='Fed', dataname2='Fasted', factor=1.5);   # generates a bagplot from the calculated footprinting depths

}

